vich_uploader:
    db_driver: orm
    metadata:
      type: attribute

    mappings:
        imagesarticles:
            uri_prefix: /images
            upload_destination: '%kernel.project_dir%/public/images/article'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            