controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

elfinder:
     resource: "@FMElfinderBundle/Resources/config/routing.yaml"